repos:
  - repo: local
    hooks:
      - id: install
        name: install package
        entry: poetry install
        language: python
        always_run: true
        pass_filenames: false
      - id: pytest
        name: run test suite
        entry: poetry run pytest
        language: python
        always_run: true
        pass_filenames: false
      - id: black
        name: check code style
        entry: poetry run black --check
        language: python
        files: "portion/.*\\.py"
