repos:
  - repo: local
    hooks:
      - id: pytest
        name: run test suite
        entry: pytest
        language: python
        always_run: true
        pass_filenames: false
      - id: black
        name: check code style
        entry: black --check portion
        language: python
        pass_filenames: false
        always_run: true
