repos:
  - repo: local
    hooks:
      - id: black
        name: check code style
        entry: poetry run black --check
        language: python
        pass_filenames: true
        types: ["python"]
      - id: pytest
        name: run test suite
        entry: poetry run pytest
        language: python
        always_run: true
        pass_filenames: false

