language: python
sudo: required
dist: bionic
python:
- 3.6
- 3.7
- 3.8
- 3.9
- pypy3
before_install:
- pip install poetry
- poetry run pip install coverage coveralls
install:
- poetry install
- poetry update
script:
- poetry run coverage run --source portion -m pytest
after_success:
- poetry run coveralls
before_deploy:
- poetry build
- poetry config pypi-token.pypi $PYPI_TOKEN
deploy:
  provider: script
  script: poetry publish
  on:
    branch: master
    tags: true
    python: 3.9
