os: linux
language: python
dist: focal
python:
- 3.6
- 3.7
- 3.8
- 3.9
- 3.10-dev
- pypy3
jobs:
  allow_failures:
    - python: 3.10-dev
    - python: pypy3
before_install:
- pip install pip virtualenv -U
- curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
- poetry run pip install coverage coveralls
install:
- poetry update --lock
- poetry install
script:
- poetry run coverage run --source portion -m pytest
after_success:
- poetry run coveralls
before_deploy:
- poetry build
- poetry config pypi-token.pypi $PYPI_TOKEN
deploy:
  provider: script
  script: poetry publish
  on:
    branch: master
    tags: true
    python: 3.9
