"""
This type stub file was generated by pyright.
"""

__all__ = ["create_api"]

def partial(
    wrapped, *args, **kwargs
):  # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
    """
    Convenient helper that combines functools.update_wrapper and
    functools.partial. It has exactly the same signature than functools.partial.
    """
    ...

def create_api(interval, *, interval_dict=..., name=...):  # -> ModuleType:
    """Create a spe

    Dynamically create a module whose API is similar to the one of portion, but
    configured to use given Interval class. Unless specified, a new IntervalDict
    subclass is automatically generated to use given Interval subclass.

    This feature is experimental, and may be changed even in minor or patch
    updates of portion.

    :param interval: a subclass of Interval.
    :param interval_dict: a subclass of IntervalDict.
    :param name: the name of the new module.
    """
    ...
