"""
This type stub file was generated by pyright.
"""

import enum

"""
This type stub file was generated by pyright.
"""
class Bound(enum.Enum):
    """
    Bound types, either CLOSED for inclusive, or OPEN for exclusive.
    """
    CLOSED = ...
    OPEN = ...
    def __bool__(self):
        ...
    
    def __invert__(self):
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self):
        ...
    


class _Singleton:
    __instance = ...
    def __new__(cls, *args, **kwargs):
        ...
    


class _PInf(_Singleton):
    """
    Represent positive infinity.
    """
    def __neg__(self):
        ...
    
    def __lt__(self, o) -> bool:
        ...
    
    def __le__(self, o) -> bool:
        ...
    
    def __gt__(self, o) -> bool:
        ...
    
    def __ge__(self, o) -> bool:
        ...
    
    def __eq__(self, o) -> bool:
        ...
    
    def __repr__(self):
        ...
    
    def __hash__(self) -> int:
        ...
    


class _NInf(_Singleton):
    """
    Represent negative infinity.
    """
    def __neg__(self):
        ...
    
    def __lt__(self, o) -> bool:
        ...
    
    def __le__(self, o) -> bool:
        ...
    
    def __gt__(self, o) -> bool:
        ...
    
    def __ge__(self, o) -> bool:
        ...
    
    def __eq__(self, o) -> bool:
        ...
    
    def __repr__(self):
        ...
    
    def __hash__(self) -> int:
        ...
    


inf = ...
